### ISSUE TITLE
Recursos para programação

### ISSUE THREAD

**Issue by Lboldrin95** [GuilhermeSilveira93/Projeto-de-Aprendizagem#1]
_Fala meu pequeno amigo, tudo bem?_

Estava dando uma olhada no conteúdo do seu **Github**, e reparei que está iniciando agora na área de programação!! 
Show muito bem, estamos nessa juntos e espero que consiga estar se desenvolvendo como um profissional da área! 

Vou estar te passando algumas dicas para o seu desenvolvimento... 

1. **Estar sempre atento a tudo que for fazer, e não fazer nada com pressa!** 

2. **Sempre digitar o conteúdo da sua programação em plataformas que sejam _AUTO-SAVE!_**

3. **Mantenha uma constância de aprendizagem, evoluindo um pouco de cada vez!**

Segue um link  de ensino bem tranquilo para o seu desenvolvimento! 
[Clique aqui no Link <-](https://www.youtube.com/watch?v=8WjAyhIFz7w)

Desejo sucesso na carreira e boa sorte!

Att,

![logo lb](https://user-images.githubusercontent.com/69554628/90137253-c247ea00-dd4b-11ea-979d-583266c76225.jpg)

**Comment by GuilhermeSilveira93** [comment]
Muito obrigado @Lboldrin95
